name: Build

on:
  push:
    tags:
      - v*


jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:

          - aarch64_generic
          - i386_pentium-mmx
          - loongarch64_generic
          - mips_mips32
          - mipsel_24kc
          - mipsel_mips32
          - x86_64

    - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@go1.24
        env:
          ARCH: ${{ matrix.arch }}-openwrt-24.10
          FEEDNAME: packages_ci
          PACKAGES: luci-app-kucat-config
          NO_REFRESH_CHECK: true

    - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
    
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          imagebuilder/bin/packages/x86_64/base/*.ipk
        tag_name: package-${{ github.run_id }}
        name: Custom Package Build
        body: "Automatically built ImmortalWrt package"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
